### ISSUE TITLE
eventConsumer example typo?

### ISSUE THREAD

**Issue by AlhasanIQ** [latolukasz/beeorm-doc#3]
On [this line](https://github.com/latolukasz/beeorm-doc/blob/6ded6b00cb80050b13974fff2502e71978a2faab/docs/guide/event_broker.md?plain=1#L198), it says that the "above example**s** never print FINISHED",
However, in the [first example](https://github.com/latolukasz/beeorm-doc/blob/6ded6b00cb80050b13974fff2502e71978a2faab/docs/guide/event_broker.md?plain=1#L163), it does say finished.
Which one is right?

**Comment by latolukasz** [comment]
U are right, fixed
